<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48</TargetFrameworks>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
    <GenerateNeutralResourcesLanguageAttribute>false</GenerateNeutralResourcesLanguageAttribute>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
    <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="**\*.xml" />
  </ItemGroup>
  <PropertyGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <DefineConstants>$(DefineConstants);FEATURE_VALIDATION;FEATURE_SGEN</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net48|AnyCPU'">
    <NoWarn>1701;1702;1705;CS1589</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="SEeF\Samples\20160704_SEeF - Voorbeeldfactuur 001 - levering.xml" />
    <None Remove="SEeF\Samples\20170713_SEeF - Voorbeeldfactuur 001 - levering.xml" />
    <None Remove="SEeF\Samples\20190326_SEeF 3.0  - Voorbeeldfactuur 001 - levering.xml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="FluentAssertions" Version="8.8.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Condition=" $(DefineConstants.Contains('FEATURE_VALIDATION')) ">
    <ProjectReference Include="..\UblSharp.Validation\UblSharp.Validation.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\UblSharp.HRExt\UblSharp.HRExt.csproj" />
    <ProjectReference Include="..\UblSharp.SCSN\UblSharp.SCSN.csproj" />
    <ProjectReference Include="..\UblSharp\UblSharp.csproj" />
    <ProjectReference Include="..\UblSharp.SEeF\UblSharp.SEeF.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>
</Project>
