// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Manual changes to this file will be overwritten if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------
namespace UblSharp.HRExt
{
    using UblSharp;
    using UblSharp.UnqualifiedDataTypes;
    
    
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("HRFISK20Data", Namespace = "urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1")]
    [System.Xml.Serialization.XmlRootAttribute("HRFISK20Data", Namespace = "urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1", IsNullable=false)]
    public partial class HRFISK20DataType
    {
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("HRObracunPDVPoNaplati", Order=0)]
        public HRObracunPDVPoNaplatiType @__HRObracunPDVPoNaplati;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("HRTaxTotal", Order=1)]
        public HRTaxTotalType @__HRTaxTotal;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("HRLegalMonetaryTotal", Order=2)]
        public HRMonetaryTotalType @__HRLegalMonetaryTotal;
        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public HRObracunPDVPoNaplatiType HRObracunPDVPoNaplati
        {
            get
            {
                if (__HRObracunPDVPoNaplati == null) { __HRObracunPDVPoNaplati = new HRObracunPDVPoNaplatiType(); }
                return __HRObracunPDVPoNaplati;
            }
            set
            {
                __HRObracunPDVPoNaplati = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public HRTaxTotalType HRTaxTotal
        {
            get
            {
                if (__HRTaxTotal == null) { __HRTaxTotal = new HRTaxTotalType(); }
                return __HRTaxTotal;
            }
            set
            {
                __HRTaxTotal = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public HRMonetaryTotalType HRLegalMonetaryTotal
        {
            get
            {
                if (__HRLegalMonetaryTotal == null) { __HRLegalMonetaryTotal = new HRMonetaryTotalType(); }
                return __HRLegalMonetaryTotal;
            }
            set
            {
                __HRLegalMonetaryTotal = value;
            }
        }

    }
    
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("HRObracunPDVPoNaplatiType", Namespace = "urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1", IsNullable=true)]
    public partial class HRObracunPDVPoNaplatiType : TextType
    {
        
        public static implicit operator HRObracunPDVPoNaplatiType(string value)
        {
             return value == null ? null : new HRObracunPDVPoNaplatiType { Value = value };
        }

        public static implicit operator string(HRObracunPDVPoNaplatiType value)
        {
             return value.Value;
        }

    }
    
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("HRMonetaryTotalType", Namespace = "urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1", IsNullable=true)]
    public partial class HRMonetaryTotalType
    {
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("TaxExclusiveAmount", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=0)]
        public AmountType @__TaxExclusiveAmount;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("OutOfScopeOfVATAmount", Order=1)]
        public OutOfScopeOfVATAmountType @__OutOfScopeOfVATAmount;
        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public AmountType TaxExclusiveAmount
        {
            get
            {
                if (__TaxExclusiveAmount == null) { __TaxExclusiveAmount = new AmountType(); }
                return __TaxExclusiveAmount;
            }
            set
            {
                __TaxExclusiveAmount = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public OutOfScopeOfVATAmountType OutOfScopeOfVATAmount
        {
            get
            {
                if (__OutOfScopeOfVATAmount == null) { __OutOfScopeOfVATAmount = new OutOfScopeOfVATAmountType(); }
                return __OutOfScopeOfVATAmount;
            }
            set
            {
                __OutOfScopeOfVATAmount = value;
            }
        }

    }
    
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AccountingCurrencyPayableAmountType", Namespace = "urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1", IsNullable=true)]
    public partial class AccountingCurrencyPayableAmountType : AmountType
    {
    }
    
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("OutOfScopeOfVATAmountType", Namespace = "urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1", IsNullable=true)]
    public partial class OutOfScopeOfVATAmountType : AmountType
    {
    }
    
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("HRTaxSchemeType", Namespace = "urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1", IsNullable=true)]
    public partial class HRTaxSchemeType
    {
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("ID", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=0)]
        public IdentifierType @__ID;
        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public IdentifierType ID
        {
            get
            {
                if (__ID == null) { __ID = new IdentifierType(); }
                return __ID;
            }
            set
            {
                __ID = value;
            }
        }

    }
    
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("HRTaxCategoryType", Namespace = "urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1", IsNullable=true)]
    public partial class HRTaxCategoryType
    {
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("ID", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=0)]
        public IdentifierType @__ID;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("Name", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=1)]
        public NameType @__Name;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("Percent", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=2)]
        public PercentType @__Percent;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("TaxExemptionReasonCode", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=3)]
        public CodeType @__TaxExemptionReasonCode;
        
        private System.Collections.Generic.List<TextType> _taxExemptionReason;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("TaxExemptionReason", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=4)]
        public TextType[] @__TaxExemptionReason
        {
            get
            {
                return _taxExemptionReason?.ToArray();
            }
            set
            {
                _taxExemptionReason = value == null ? null : new System.Collections.Generic.List<TextType>(value);
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("HRTaxScheme", Order=5)]
        public HRTaxSchemeType @__HRTaxScheme;
        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<TextType> TaxExemptionReason
        {
            get { return _taxExemptionReason ?? (_taxExemptionReason = new System.Collections.Generic.List<TextType>()); }
            set { _taxExemptionReason = value; }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public IdentifierType ID
        {
            get
            {
                if (__ID == null) { __ID = new IdentifierType(); }
                return __ID;
            }
            set
            {
                __ID = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public NameType Name
        {
            get
            {
                if (__Name == null) { __Name = new NameType(); }
                return __Name;
            }
            set
            {
                __Name = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public PercentType Percent
        {
            get
            {
                if (__Percent == null) { __Percent = new PercentType(); }
                return __Percent;
            }
            set
            {
                __Percent = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public CodeType TaxExemptionReasonCode
        {
            get
            {
                if (__TaxExemptionReasonCode == null) { __TaxExemptionReasonCode = new CodeType(); }
                return __TaxExemptionReasonCode;
            }
            set
            {
                __TaxExemptionReasonCode = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public HRTaxSchemeType HRTaxScheme
        {
            get
            {
                if (__HRTaxScheme == null) { __HRTaxScheme = new HRTaxSchemeType(); }
                return __HRTaxScheme;
            }
            set
            {
                __HRTaxScheme = value;
            }
        }

    }
    
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("HRTaxSubtotalType", Namespace = "urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1", IsNullable=true)]
    public partial class HRTaxSubtotalType
    {
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("TaxableAmount", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=0)]
        public AmountType @__TaxableAmount;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("TaxAmount", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=1)]
        public AmountType @__TaxAmount;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("HRTaxCategory", Order=2)]
        public HRTaxCategoryType @__HRTaxCategory;
        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public AmountType TaxableAmount
        {
            get
            {
                if (__TaxableAmount == null) { __TaxableAmount = new AmountType(); }
                return __TaxableAmount;
            }
            set
            {
                __TaxableAmount = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public AmountType TaxAmount
        {
            get
            {
                if (__TaxAmount == null) { __TaxAmount = new AmountType(); }
                return __TaxAmount;
            }
            set
            {
                __TaxAmount = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public HRTaxCategoryType HRTaxCategory
        {
            get
            {
                if (__HRTaxCategory == null) { __HRTaxCategory = new HRTaxCategoryType(); }
                return __HRTaxCategory;
            }
            set
            {
                __HRTaxCategory = value;
            }
        }

    }
    
#if FEATURE_SERIALIZATION
    [System.SerializableAttribute()]
#endif
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("HRTaxTotalType", Namespace = "urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1", IsNullable=true)]
    public partial class HRTaxTotalType
    {
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("TaxAmount", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", Order=0)]
        public AmountType @__TaxAmount;
        
        private System.Collections.Generic.List<HRTaxSubtotalType> _hRTaxSubtotal;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("HRTaxSubtotal", Order=1)]
        public HRTaxSubtotalType[] @__HRTaxSubtotal
        {
            get
            {
                return _hRTaxSubtotal?.ToArray();
            }
            set
            {
                _hRTaxSubtotal = value == null ? null : new System.Collections.Generic.List<HRTaxSubtotalType>(value);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public System.Collections.Generic.List<HRTaxSubtotalType> HRTaxSubtotal
        {
            get { return _hRTaxSubtotal ?? (_hRTaxSubtotal = new System.Collections.Generic.List<HRTaxSubtotalType>()); }
            set { _hRTaxSubtotal = value; }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public AmountType TaxAmount
        {
            get
            {
                if (__TaxAmount == null) { __TaxAmount = new AmountType(); }
                return __TaxAmount;
            }
            set
            {
                __TaxAmount = value;
            }
        }

    }
}
